import React, { createContext, useContext, useState, useEffect } from 'react';

const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    scanLink: 'Scan Link',
    threatExamples: 'Threat Examples',
    threatHistory: 'Threat History',
    reports: 'Reports Center',
    rulesBookmarks: 'Rules & Bookmarks',
    fileScanner: 'File Scanner',
    safeBrowsing: 'Safe Sandbox',
    passwordChecker: 'Password Audit',
    darkWeb: 'Dark Web Alerts',
    liveMonitor: 'Live Monitor',
    community: 'Community Hub',
    leaderboard: 'Leaderboard',
    challenges: 'Safety Challenges',
    settings: 'System Settings',
    systemActive: 'System Active',
    activeGuard: 'Active Guard',
    totalScans: 'Total Scans',
    blockedThreats: 'Blocked Threats',
    suspiciousLinks: 'Suspicious Links',
    safeUrls: 'Safe URLs',
    scanUrlPlaceholder: 'Enter or paste any suspicious URL (e.g. http://paypal-verify.top)...',
    scanButton: 'Scan Target URL',
    scanning: 'Analyzing Target...',
    voiceAssistant: 'Cyber Voice Assistant',
    forEducationalPurposes: 'For Educational Purposes Only',
    phishing: 'Phishing',
    malware: 'Malware',
    suspicious: 'Suspicious',
    fakeOffer: 'Fake Offer',
    safe: 'Safe',
    riskScore: 'Risk Score',
    confidence: 'AI Confidence',
    inspectThreat: 'Inspect Threat',
    bgTheme: 'Cyber Theme'
  },
  es: {
    dashboard: 'Panel Principal',
    scanLink: 'Escanear Enlace',
    threatExamples: 'Ejemplos de Amenazas',
    threatHistory: 'Historial de Amenazas',
    reports: 'Centro de Informes',
    rulesBookmarks: 'Reglas y Marcadores',
    fileScanner: 'Escáner de Archivos',
    safeBrowsing: 'Navegación Segura',
    passwordChecker: 'Auditoría de Contraseña',
    darkWeb: 'Alertas de Dark Web',
    liveMonitor: 'Monitor en Vivo',
    community: 'Comunidad',
    leaderboard: 'Tabla de Clasificación',
    challenges: 'Desafíos de Seguridad',
    settings: 'Configuración del Sistema',
    systemActive: 'Sistema Activo',
    activeGuard: 'Protección Activa',
    totalScans: 'Total de Análisis',
    blockedThreats: 'Amenazas Bloqueadas',
    suspiciousLinks: 'Enlaces Sospechosos',
    safeUrls: 'URLs Seguras',
    scanUrlPlaceholder: 'Ingrese o pegue una URL sospechosa...',
    scanButton: 'Escanear URL Objetivo',
    scanning: 'Analizando Objetivo...',
    voiceAssistant: 'Asistente de Voz Cyber',
    forEducationalPurposes: 'Solo para Fines Educativos',
    phishing: 'Suplantación',
    malware: 'Malware',
    suspicious: 'Sospechoso',
    fakeOffer: 'Oferta Falsa',
    safe: 'Seguro',
    riskScore: 'Puntuación de Riesgo',
    confidence: 'Confianza IA',
    inspectThreat: 'Inspeccionar Amenaza',
    bgTheme: 'Tema Cibernético'
  },
  fr: {
    dashboard: 'Tableau de Bord',
    scanLink: 'Scanner un Lien',
    threatExamples: 'Exemples de Menaces',
    threatHistory: 'Historique des Menaces',
    reports: 'Centre de Rapports',
    rulesBookmarks: 'Règles & Favoris',
    fileScanner: 'Scanner de Fichiers',
    safeBrowsing: 'Navigation Sécurisée',
    passwordChecker: 'Audit de Mot de Passe',
    darkWeb: 'Alertes Dark Web',
    liveMonitor: 'Moniteur en Direct',
    community: 'Communauté',
    leaderboard: 'Classement',
    challenges: 'Défis de Sécurité',
    settings: 'Paramètres Système',
    systemActive: 'Système Actif',
    activeGuard: 'Garde Active',
    totalScans: 'Analyses Totales',
    blockedThreats: 'Menaces Bloquées',
    suspiciousLinks: 'Liens Suspects',
    safeUrls: 'URLs Sûres',
    scanUrlPlaceholder: 'Entrez ou collez une URL suspecte...',
    scanButton: 'Analyser l\'URL',
    scanning: 'Analyse en cours...',
    voiceAssistant: 'Assistant Vocal Cyber',
    forEducationalPurposes: 'À des fins éducatives uniquement',
    phishing: 'Hameçonnage',
    malware: 'Logiciel Malveillant',
    suspicious: 'Suspect',
    fakeOffer: 'Fausse Offre',
    safe: 'Sûr',
    riskScore: 'Score de Risque',
    confidence: 'Confiance IA',
    inspectThreat: 'Inspecter la Menace',
    bgTheme: 'Thème Cyber'
  },
  de: {
    dashboard: 'Übersicht',
    scanLink: 'Link Überprüfen',
    threatExamples: 'Bedrohungsbeispiele',
    threatHistory: 'Bedrohungsverlauf',
    reports: 'Berichtszentrum',
    rulesBookmarks: 'Regeln & Lesezeichen',
    fileScanner: 'Datei-Scanner',
    safeBrowsing: 'Sicheres Surfen',
    passwordChecker: 'Passwort-Audit',
    darkWeb: 'Darknet-Warnungen',
    liveMonitor: 'Live-Monitor',
    community: 'Community-Hub',
    leaderboard: 'Rangliste',
    challenges: 'Sicherheits-Challenges',
    settings: 'Systemeinstellungen',
    systemActive: 'System Aktiv',
    activeGuard: 'Aktiver Schutz',
    totalScans: 'Gesamtüberprüfungen',
    blockedThreats: 'Blockierte Bedrohungen',
    suspiciousLinks: 'Verdächtige Links',
    safeUrls: 'Sichere URLs',
    scanUrlPlaceholder: 'Verdächtige URL eingeben oder einfügen...',
    scanButton: 'Ziel-URL Überprüfen',
    scanning: 'Wird analysiert...',
    voiceAssistant: 'Cyber Sprachassistent',
    forEducationalPurposes: 'Nur zu Bildungszwecken',
    phishing: 'Phishing',
    malware: 'Schadsoftware',
    suspicious: 'Verdächtig',
    fakeOffer: 'Falsches Angebot',
    safe: 'Sicher',
    riskScore: 'Risikobewertung',
    confidence: 'KI-Vertrauen',
    inspectThreat: 'Bedrohung Inspizieren',
    bgTheme: 'Cyber-Design'
  },
  ja: {
    dashboard: 'ダッシュボード',
    scanLink: 'リンクをスキャン',
    threatExamples: '脅威のサンプル',
    threatHistory: 'スキャン履歴',
    reports: 'セキュリティレポート',
    rulesBookmarks: 'ルール＆ブックマーク',
    fileScanner: 'ファイルスキャナー',
    safeBrowsing: '安全サンドボックス',
    passwordChecker: 'パスワード診断',
    darkWeb: 'ダークウェブ警告',
    liveMonitor: 'リアルタイム監視',
    community: 'コミュニティ',
    leaderboard: 'ランキング',
    challenges: 'セキュリティクイズ',
    settings: 'システム設定',
    systemActive: 'システム作動中',
    activeGuard: 'リアルタイム保護',
    totalScans: '総スキャン数',
    blockedThreats: 'ブロックした脅威',
    suspiciousLinks: '不審なリンク',
    safeUrls: '安全なURL',
    scanUrlPlaceholder: '不審なURLを入力または貼り付け...',
    scanButton: 'URLをAIスキャン',
    scanning: '脅威を分析中...',
    voiceAssistant: 'AI音声アシスタント',
    forEducationalPurposes: '教育および啓発目的のみ',
    phishing: 'フィッシング',
    malware: 'マルウェア',
    suspicious: '不審',
    fakeOffer: '詐欺オファー',
    safe: '安全',
    riskScore: 'リスクスコア',
    confidence: 'AI信頼度',
    inspectThreat: '詳細診断',
    bgTheme: 'サイバーテーマ'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    scanLink: 'लिंक स्कैन करें',
    threatExamples: 'खतरे के उदाहरण',
    threatHistory: 'स्कैन इतिहास',
    reports: 'सुरक्षा रिपोर्ट',
    rulesBookmarks: 'नियम और बुकमार्क',
    fileScanner: 'फ़ाइल स्कैनर',
    safeBrowsing: 'सुरक्षित ब्राउज़िंग',
    passwordChecker: 'पासवर्ड जांच',
    darkWeb: 'डार्क वेब अलर्ट',
    liveMonitor: 'लाइव मॉनिटर',
    community: 'कम्युनिटी हब',
    leaderboard: 'लीडरबोर्ड',
    challenges: 'सुरक्षा चुनौतियाँ',
    settings: 'सिस्टम सेटिंग्स',
    systemActive: 'सिस्टम सक्रिय',
    activeGuard: 'सक्रिय सुरक्षा',
    totalScans: 'कुल स्कैन',
    blockedThreats: 'अवरुद्ध खतरे',
    suspiciousLinks: 'संदिग्ध लिंक',
    safeUrls: 'सुरक्षित यूआरएल',
    scanUrlPlaceholder: 'संदिग्ध यूआरएल दर्ज करें या चिपकाएं...',
    scanButton: 'यूआरएल स्कैन करें',
    scanning: 'विश्लेषण जारी है...',
    voiceAssistant: 'साइबर वॉयस असिस्टेंट',
    forEducationalPurposes: 'केवल शैक्षिक उद्देश्यों के लिए',
    phishing: 'फ़िशिंग',
    malware: 'मालवेयर',
    suspicious: 'संदिग्ध',
    fakeOffer: 'फर्जी ऑफर',
    safe: 'सुरक्षित',
    riskScore: 'जोखिम स्कोर',
    confidence: 'एआई विश्वास',
    inspectThreat: 'खतरे की जांच करें',
    bgTheme: 'साइबर थीम'
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('cybershield_language') || 'en');

  const changeLanguage = (newLang) => {
    if (TRANSLATIONS[newLang]) {
      setLang(newLang);
      localStorage.setItem('cybershield_language', newLang);
    }
  };

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t, availableLanguages: Object.keys(TRANSLATIONS) }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLang must be used within a LanguageProvider');
  }
  return context;
};
